gloo:
  settings:
    disableKubernetesDestinations: true
  discovery:
    enabled: true
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        accessLoggingService:
          accessLog:
          - fileSink:
              path: /dev/stdout
              stringFormat: ""